## Pivot tables

In [1]:
import pandas as pd

In [2]:


sales_data = {
    "date": pd.date_range(start="2025-01-01", periods=20, freq="15D"),
    "product": [
        "A", "B", "C", "D", "A",
        "B", "C", "D", "A", "B",
        "C", "D", "A", "B", "C",
        "D", "A", "B", "C", "D"
    ],
    "region": [
        "North", "South", "East", "West", "North",
        "East", "South", "West", "North", "South",
        "East", "West", "North", "South", "East",
        "West", "North", "South", "East", "West"
    ],
    "sales": [
        450, 720, 380, 910, 650,
        540, 860, 430, 790, 610,
        500, 980, 340, 890, 760,
        680, 520, 940, 470, 830
    ],
    "units": [
        45, 72, 38, 91, 65,
        54, 86, 43, 79, 61,
        50, 98, 34, 89, 76,
        68, 52, 94, 47, 83
    ],
    "rep": [
        "Alice", "Bob", "Charlie", "David", "Emma",
        "Frank", "Grace", "Henry", "Alice", "Bob",
        "Charlie", "David", "Emma", "Frank", "Grace",
        "Henry", "Alice", "Bob", "Charlie", "David"
    ],
    "month": [
        "Jan", "Jan", "Jan", "Feb", "Feb",
        "Feb", "Mar", "Mar", "Mar", "Apr",
        "Apr", "Apr", "May", "May", "May",
        "Jun", "Jun", "Jun", "Jul", "Jul"
    ],
    "quarter": [
        "Q1", "Q1", "Q1", "Q1", "Q1",
        "Q1", "Q1", "Q1", "Q1", "Q2",
        "Q2", "Q2", "Q2", "Q2", "Q2",
        "Q2", "Q2", "Q2", "Q3", "Q3"
    ]
}

df = pd.DataFrame(sales_data)

print(df)

         date product region  sales  units      rep month quarter
0  2025-01-01       A  North    450     45    Alice   Jan      Q1
1  2025-01-16       B  South    720     72      Bob   Jan      Q1
2  2025-01-31       C   East    380     38  Charlie   Jan      Q1
3  2025-02-15       D   West    910     91    David   Feb      Q1
4  2025-03-02       A  North    650     65     Emma   Feb      Q1
5  2025-03-17       B   East    540     54    Frank   Feb      Q1
6  2025-04-01       C  South    860     86    Grace   Mar      Q1
7  2025-04-16       D   West    430     43    Henry   Mar      Q1
8  2025-05-01       A  North    790     79    Alice   Mar      Q1
9  2025-05-16       B  South    610     61      Bob   Apr      Q2
10 2025-05-31       C   East    500     50  Charlie   Apr      Q2
11 2025-06-15       D   West    980     98    David   Apr      Q2
12 2025-06-30       A  North    340     34     Emma   May      Q2
13 2025-07-15       B  South    890     89    Frank   May      Q2
14 2025-07-30       C   East    760     76    Grace   May      Q2
15 2025-08-14       D   West    680     68    Henry   Jun      Q2
16 2025-08-29       A  North    520     52    Alice   Jun      Q2
17 2025-09-13       B  South    940     94      Bob   Jun      Q2
18 2025-09-28       C   East    470     47  Charlie   Jul      Q3
19 2025-10-13       D   West    830     83    David   Jul      Q3

In [4]:
pd.pivot_table(df,"sales",index="region" ,columns="product", aggfunc="max")

product      A      B      C      D
region
East       NaN  540.0  760.0    NaN
North    790.0    NaN    NaN    NaN
South      NaN  940.0  860.0    NaN
West       NaN    NaN    NaN  980.0

In [5]:
pd.pivot_table(df,"sales",index="region" ,columns="product", aggfunc="min")

product      A      B      C      D
region
East       NaN  540.0  380.0    NaN
North    340.0    NaN    NaN    NaN
South      NaN  610.0  860.0    NaN
West       NaN    NaN    NaN  430.0

## OPERATIONS

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     20 non-null     datetime64[us]
 1   product  20 non-null     str
 2   region   20 non-null     str
 3   sales    20 non-null     int64
 4   units    20 non-null     int64
 5   rep      20 non-null     str
 6   month    20 non-null     str
 7   quarter  20 non-null     str
dtypes: datetime64[us](1), int64(2), str(5)
memory usage: 1.4 KB

In [9]:
df.shape

(20, 8)

In [11]:
df.columns

Index(['date', 'product', 'region', 'sales', 'units', 'rep', 'month',
       'quarter'],
      dtype='str')

In [13]:
df.describe()

                      date     sales     units
count                   20   20.0000  20.00000
mean   2025-05-23 12:00:00  662.5000  66.25000
min    2025-01-01 00:00:00  340.0000  34.00000
25%    2025-03-13 06:00:00  492.5000  49.25000
50%    2025-05-23 12:00:00  665.0000  66.50000
75%    2025-08-02 18:00:00  837.5000  83.75000
max    2025-10-13 00:00:00  980.0000  98.00000
std                    NaN  201.5695  20.15695